name: galleryimage
description: Flutter plugin that list of images from URLs allows you to display
  and zoomable multi image on iOS and Android.
version: 2.0.1 # Consider bumping version after adding features
homepage: https://github.com/BeshoyMelika/flutter-gallery-package

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1 # Updated version
  video_player: ^2.10.1 # Added for video playback
  chewie: ^1.13.0 # Added for video player UI controls
  video_thumbnail: ^0.5.6
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true